spring:

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5444/book_store_db
    username: postgres
    password: root

  flyway:
    url: jdbc:postgresql://localhost:5444/book_store_db
    user: postgres
    password: root

  sql:
    init:
      mode: always

grpc:
  server:
    port: 9080


